### ISSUE TITLE
touchIdAny is deprecated

### ISSUE THREAD

**Issue by netgfx** [remarcus/flutter_biometrics#2]
Apple suggests using `biometryAny` instead
https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/1617988-touchidany

or better yet https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/1392879-userpresence to offer more functionality with passcode fallback.

I could create a PR if that is desirable. But not sure how to tackle the Android part to also accept passcode as a fallback.

**Comment by lukas-travelunion** [comment]
Hi Michael,

I have updated the constraint for later versions of iOS with commit 0ff18d4124300d95e04d6b9dd6ce69976e92d34a

Currently, we don't want to support passcode fallback in our app, for which this package was initially created, but I will add this functionality, as you opened #1 I will close this one.

Thank you for your help :)
