### ISSUE TITLE
Error with local_auth

### ISSUE THREAD

**Issue by netgfx** [remarcus/flutter_biometrics#3]
Error: 'BiometricType' is imported from both 'package:local_auth/local_auth.dart' and 'package:flutter_biometrics/flutter_biometrics.dart'.
import 'package:flutter_biometrics/flutter_biometrics.dart';

**Comment by lukas-travelunion** [comment]
Hi Michael,

Thanks for your feedback.

As it was forked from local auth naming stayed the same for some elements.

I have updated the naming slightly to avoid this issue with commit eee3bf81ba8af5dc8b49169e1831840b8f873fe0 and did some additional cleanup.

Hope this will solve the issue.
